name: Deploy NGSA-Memory

on:
  push:
    branches:
      - main

    paths:
    - gitops/**
    - '.github/workflows/gitops.yaml'

jobs:

  deploy:

    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: ghcr.io/retaildevcrews/tinybench

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_ID }}
        password: ${{ secrets.GHCR_PAT }}

    - name: GitOps Deploy
      run: |
        dotnet tool install -g autogitops
        ago -u ${{ secrets.GHCR_ID }} -p ${{ secrets.GHCR_PAT }} -r /retaildevcrews/gitops
